<?php 
  session_start(); 

  if (!isset($_SESSION['username'])) {
        $_SESSION['msg'] = "You must log in first";
        header('location: register/login.php');
  }
  if (isset($_GET['logout'])) {
        session_destroy();
        unset($_SESSION['username']);
        header("location: register/login.php");
  }
?>


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Terms of Service | Help</title>

    <!-- favicon -->
    <link href="assets/img/favicon.png" rel=icon>

    <!-- web-fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css'>

    <!-- Bootstrap -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- font-awesome -->
    <link href="assets/fonts/font-awesome/font-awesome.min.css" rel="stylesheet">
    <!-- Mobile Menu Style -->
    <link href="assets/css/mobile-menu.css" rel="stylesheet">

    <!-- Owl carousel -->
    <link href="assets/css/owl.carousel.css" rel="stylesheet">
    <link href="assets/css/owl.theme.default.min.css" rel="stylesheet">
    <!-- Theme Style -->
    <link href="assets/css/style.css" rel="stylesheet">
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar">
<div id="main-wrapper">
<!-- Page Preloader -->
<div id="preloader">
    <div id="status">
        <div class="status-mes"></div>
    </div>
</div>
<!-- preloader -->

<div class="uc-mobile-menu-pusher">


<?php include ("includes/header.php"); ?>

<div id="container1">
  <div class="content-wrapper">
    <div id="content">

    <p><em>Last Updated on May 10, 2024</em></p>
<p>This page describes the terms and conditions that govern your use of certain New York Times products or services, including NYTimes.com and mobile applications, offered by The New York Times Company and its subsidiaries, including The Athletic (<span style="color: #333333; font-family: NYTFranklinMedium; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">“</span>NYT<span style="color: #333333; font-family: NYTFranklinMedium; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: #ffffff; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">”</span>, “us” or “we”).</p>
<p><strong>PLEASE READ THESE TERMS CAREFULLY BEFORE USING ANY NYT PRODUCTS OR SERVICES, AS THESE TERMS AFFECT YOUR LEGAL RIGHTS.</strong></p>
<p><strong>IMPORTANT NOTICE - ARBITRATION AGREEMENT AND CLASS ACTION WAIVER:</strong> BY AGREEING TO BE BOUND BY THE TERMS OF SERVICE, YOU AGREE THAT ALL DISPUTES BETWEEN US WILL BE RESOLVED BY BINDING ARBITRATION, EXCEPT FOR CERTAIN LIMITED TYPES OF DISPUTES DESCRIBED IN <a href="#12" target="_self">SECTION 12</a> BELOW. YOUR AGREEMENT TO ARBITRATION MEANS YOU ARE GIVING UP THE RIGHT TO GO TO COURT AND THE RIGHT TO A TRIAL BY JURY, AND INSTEAD, DISPUTES WILL BE DECIDED BY A NEUTRAL ARBITRATOR. YOU ALSO AGREE THAT ALL DISPUTES BETWEEN US, WHETHER IN COURT OR IN ARBITRATION, WILL BE BROUGHT ONLY ON AN INDIVIDUAL BASIS AND YOU ARE WAIVING YOUR RIGHT TO BRING OR PARTICIPATE IN A CLASS ARBITRATION OR CLASS ACTION. PLEASE CLICK <a href="#12" target="_self">HERE</a> TO READ SECTION 12 OF THIS AGREEMENT FOR FURTHER DETAILS.</p>
<p>For information on how NYT collects, uses and shares any personal information, please see our <a href="https://www.nytimes.com/privacy/privacy-policy" target="_blank" rel="noopener">Privacy Policy</a>. <span style="font-weight: 400;">If you reside outside of the European Economic Area, your acceptance of these Terms of Service constitutes your consent to the processing activities described in our </span><a href="https://www.nytimes.com/privacy/privacy-policy" target="_blank" rel="noopener">Privacy Policy</a><span style="font-weight: 400;"> under the laws of your jurisdiction.</span></p>
<p><span style="font-weight: 400;"><strong>Table of Contents</strong></span></p>
<ol>
<li><a href="#1"><span style="font-weight: 400;"> GENERAL RULES AND DEFINITIONS</span></a></li>
<li><a href="#2"><span style="font-weight: 400;"> CONTENT ON THE SERVICES</span></a></li>
<li><a href="#3"><span style="font-weight: 400;"> USER-GENERATED CONTENT: SUBMISSIONS, INCLUDING COMMENTS AND MORE</span></a></li>
<li><a href="#4"><span style="font-weight: 400;"> PROHIBITED USE OF THE SERVICES</span></a></li>
<li><a href="#5"><span style="font-weight: 400;"> REPRESENTATIONS AND WARRANTIES; INDEMNIFICATION; LIMITATION OF LIABILITIES</span></a></li>
<li><a href="#6"><span style="font-weight: 400;"> REGISTRATION AND SECURITY</span></a></li>
<li><a href="#7"><span style="font-weight: 400;"> FEES AND PAYMENTS</span></a></li>
<li><a href="#8"><span style="font-weight: 400;"> THIRD-PARTY CONTENT AND LINKS TO THIRD-PARTY WEBSITES</span></a></li>
<li><a href="#9">SOFTWARE LICENSES</a></li>
<li><a href="#10">TERMINATION</a></li>
<li><span style="font-weight: 400;"><a href="#11"> GOVERNING LAW; JURISDICTION</a></span></li>
<li><span style="font-weight: 400;"><a href="#12" target="_self" rel="undefined">WAIVER OF CLASS ACTIONS; ARBITRATION</a></span></li>
<li><a href="#13" target="_self" rel="undefined">MISCELLANEOUS</a></li>
<li><a href="#14" target="_self" rel="undefined">SPECIAL TERMS</a></li>
</ol>
<p><a name="1"></a><strong>1. GENERAL RULES AND DEFINITIONS</strong></p>
<p><span style="font-weight: 400;">1.1 If you choose to use certain NYT products or services displaying or otherwise governed by these Terms of Service, including NYTimes.com (the “</span><strong>Site</strong><span style="font-weight: 400;">”), NYT’s mobile sites and applications (including Cooking, Games or The Athletic), any of the features of the Site, including but not limited to RSS feeds, APIs, and Software (as defined below) and other downloads, and NYT’s Home Delivery service (collectively, the “</span><strong>Services<span style="font-weight: 400;">”</span></strong><span style="font-weight: 400;">), you will be agreeing to abide by all of the terms and conditions of these Terms of Service between you and NYT.</span></p>
<p><span style="font-weight: 400;">1.2 We may change, add or remove portions of these Terms of Service at any time by notifying you of the change in writing (including by email or by updating the date above after “Last Updated On”). Such changes will become effective immediately upon posting. It is your responsibility to review these Terms of Service prior to each use of the Site.</span></p>
<p><span style="font-weight: 400;">1.3 IF ANY OF THE TERMS AND CONDITIONS OF THESE TERMS OF SERVICE, OR ANY FUTURE CHANGES, ARE UNACCEPTABLE TO YOU, YOU MAY: (1) CANCEL YOUR ACCOUNT (</span><span style="font-weight: 400;">SEE <a href="#10.1" target="_self">SECTION 10.1</a> REGARDING TERMINATION OF SERVICE) AND/OR (2) DISCONTINUE YOUR USE OF THE SERVICES. YOUR CONTINUED USE OF THE SERVICES NOW, OR FOLLOWING THE POSTING OF UPDATED TERMS OF SERVICE, WILL INDICATE ACCEPTANCE BY YOU OF SUCH TERMS OF SERVICE, CHANGES, OR MODIFICATIONS.</span></p>
<p><span style="font-weight: 400;">1.4 We may change, suspend or discontinue any aspect of the Services at any time, including the availability of any Services feature, database, or content. We may also impose limits on certain features and services or restrict your access to parts or all of the Services without notice or liability.</span></p>
<p><span style="font-weight: 400;">1.5 Being exposed to advertising is a condition of accessing the Services.</span></p>
        1. 2. CONTENT ON THE SERVICES</button>
        <div class="content">

        <p>2.1 The contents of the Services, including the Site, are intended for your personal, non-commercial use. All materials published or available on the Services (including, but not limited to text, photographs, images, illustrations, designs, audio clips, video clips, “look and feel,” metadata, data, or compilations, all also known as the “<strong>Content</strong>”) are protected by copyright, and owned or controlled by The New York Times Company or the party credited as the provider of the Content. The New York Times Company also owns copyright in the selection, coordination, compilation, and enhancement of such Content (“<strong>Arrangement</strong>”). You shall abide by all additional copyright notices, information, or restrictions contained in any Content accessed through the Service. Non-commercial use does not include the use of Content without prior written consent from The New York Times Company in connection with: (1) the development of any software program, model, algorithm, or other generative AI tool, including, but not limited to, training or using the Content in connection with the development or operation of a machine learning or artificial intelligence (AI) system (including any use of the Content for training, fine tuning, or grounding the machine learning or AI system or as part of retrieval-augmented generation); or (2) providing archived or cached data sets containing Content to another person or entity.</p>
<p><span style="font-weight: 400;">2.2 The Services and Content are protected by copyrights, trademarks, patents, trade secrets, database rights, sui generis rights and other intellectual or proprietary rights in or to the Services and Content pursuant to U.S. and international laws. You may not modify, publish, transmit, participate in the transfer or sale of, reproduce (except as provided in <a href="#2.3" target="_self">Section 2.3</a> of these Terms of Service), create new works from, distribute, perform, display (including framing and inline linking), communicate to the public or in any way exploit, any of the Content (or its Arrangement) or the Services (including Software) in whole or in part.</span></p>
<p><a name="2.3"></a><span style="font-weight: 400;">2.3 You may download or copy the Content and other downloadable items displayed on the Services for your personal use only, provided that you maintain all copyright and other notices contained in the Content and other downloadable items. Copying or storing of any Content for other than personal use is expressly prohibited without prior written permission from </span><a href="https://help.nytimes.com/hc/en-us/articles/115014891408-Obtaining-and-using-Times-content" target="_blank" rel="noopener">The New York Times Rights and Permissions Department</a><span style="font-weight: 400;">, or the copyright holder identified in the copyright notice contained in the Content.</span></p>
<p><span style="font-weight: 400;">2.4 Certain Content is furnished by the Associated Press and Reuters, which will not be liable for any delays, inaccuracies, errors or omissions in any such Content, or in the transmission or delivery of all or any part of that Content, or for any resulting damages.</span></p>
<hr>

<p><a name="3"></a><strong><a id="discussions"></a>3. USER GENERATED CONTENT: SUBMISSIONS INCLUDING COMMENTS, READER REVIEWS AND MORE</strong></p>
<p><span style="font-weight: 400;">3.1 If you upload, post or submit any content on the Services, you represent to us that you have all the necessary legal rights to upload, post or submit such content and it will not violate any law or the rights of any person. You shall not upload to, or distribute or otherwise publish to the Services any libelous, defamatory, obscene, pornographic, abusive, or otherwise illegal material. You shall not impersonate anyone else or otherwise misrepresent your identity, affiliation or status. You agree not to provide material and misleading information knowingly and with intent to defraud. You shall not upload to, or distribute or otherwise publish to the Services any malware, viruses, spyware, or other malicious software or files to the Services. You shall not use automated means to upload to, or distribute or otherwise publish to, the Services any content.</span></p>
<p><span style="font-weight: 400;">Be courteous. You agree that you will not threaten or verbally abuse other members, use defamatory language, or deliberately disrupt discussions with repetitive messages, meaningless messages or “spam.”</span></p>
<p><span style="font-weight: 400;">Use respectful language. Like any community, the online conversation flourishes only when our members feel welcome and safe. You agree not to use language that abuses or discriminates on the basis of race, religion, nationality, gender, sexual preference, age, region, disability, etc. Hate speech of any kind is grounds for immediate and permanent suspension of access to all or part of the Services.</span></p>
<p><span style="font-weight: 400;">Debate, but don't attack. In a community full of opinions and preferences, people always disagree. NYT encourages active discussions and welcomes heated debate on the Services, but personal attacks are a direct violation of these Terms of Service and are grounds for immediate and permanent suspension of access to all or part of the Service.</span></p>
<p><span style="font-weight: 400;">For more information regarding The Athletic’s Code of Conduct, please go to <span style="color: #000000; font-family: ' Times New Roman' font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><a href="https://nytimes.com/athletic/code-of-conduct" target="_blank" rel="noopener noreferrer">nytimes.com/athletic/code-of-conduct</a></span>. </span></p>
<p><span style="font-weight: 400;">3.2 The Services may be used only in a noncommercial manner. You must not, without the express approval of NYT, distribute or otherwise publish any material containing any solicitation of funds, advertising or solicitation for goods or services. You may not use all or part of the Services to collect, store, or use any user information for any purpose not expressly permitted by these Terms of Service.</span></p>
<p><span style="font-weight: 400;">3.3 You acknowledge that any submissions you make to the Services (i.e., user-generated content including but not limited to: comments, forum messages, reviews, text, video, audio and photographs, as well as computer code and applications) (each, a “</span><strong>Submission</strong>”<span style="font-weight: 400;">) may be used, edited, removed, modified, published, transmitted, and displayed by NYT and you waive any rights you may have in having the material altered or changed in a manner not agreeable to you. Submissions made to the Services may also be included in our RSS feeds and APIs and made available for republishing through other formats.</span></p>
<p><span style="font-weight: 400;">3.4 You grant NYT a perpetual, nonexclusive, world-wide, royalty-free, sub-licensable license to the Submissions, which includes without limitation the right for NYT, or any third party it designates, to use, copy, transmit, excerpt, publish, distribute, publicly display, publicly perform, communicate to the public, create derivative works of, host, index, cache, tag, encode, modify and adapt (including without limitation the right to adapt to streaming, downloading, broadcast, mobile, digital, thumbnail, scanning or other technologies) in any form or media now known or developed at any time, any Submission posted by you on or to the Services or any other website owned by NYT, including any Submission posted on or to the Services through a third party. Among other things, NYT licenses comments to third parties for academic, governmental, financial and corporate use. In these cases, steps are taken to remove personal information from such comments.</span></p>
<p><span style="font-weight: 400;">3.5 You are solely responsible for the content of your Submissions. However, while NYT does not and cannot review every Submission and is not responsible for the content of these messages, NYT reserves the right to delete, move, or edit Submissions that it, in its sole discretion, deems abusive, defamatory, obscene, in violation of copyright or trademark laws, in violation of these Terms of Service, or otherwise unacceptable.</span></p>
<p><span style="font-weight: 400;">3.6 By making a Submission, you are consenting to its display and publication on the Site and in the Services and for related online and offline promotional uses.</span></p>
<hr>
<p><a name="4"></a><strong><a id="e"></a>4. PROHIBITED USE OF THE SERVICES</strong></p>
<p><span style="font-weight: 400;">4.1 You may not access or use, or attempt to access or use, the Services to take any action that could harm us or a third party. You may not use the Services in violation of applicable laws, including export controls and sanctions, or in violation of our or any third party’s intellectual property or other proprietary or legal rights. You further agree that you will not attempt (or encourage or support anyone else's attempt) to circumvent, reverse engineer, decrypt, or otherwise alter or interfere with the Services, or any content of the Services, or make any unauthorized use of the Services. Without NYT’s prior written consent, you shall not:</span></p>
<p><span style="font-weight: 400;">(1) access any part of the Services, Content, data or information you do not have permission or authorization to access or for which NYT has revoked your access; </span></p>
<p><span style="font-weight: 400;">(2) use robots, spiders, scripts, service, software or any manual or automatic device, tool, or process designed to data mine or scrape the Content, data or information from the Services, or otherwise use, access, or collect the Content, data or information from the Services using automated means; </span></p>
<p>(3) use the Content for the development of any software program, model, algorithm, or generative AI tool, including, but not limited to, training or using the Content in connection with the development or operation of a machine learning or artificial intelligence (AI) system (including any use of the Content for training, fine tuning, or grounding the machine learning or AI system or as part of retrieval-augmented generation).</p>
<p>(4) use services, software or any manual or automatic device, tool, or process designed to circumvent any restriction, condition, or technological measure that controls access to the Services in any way, including overriding any security feature, bypassing or circumventing any access controls or use limits of the Services, or failing to abide by exclusionary protocols such as the Robots Exclusion Protocol or the Automated Content Access protocol (NYT’s robots.txt notice does not constitute NYT’s prior written consent under these Terms of Service);</p>
<p>(5) cache or archive the Content (except for a public search engine’s use of spiders for creating search indices solely for the inclusion of links and short, non-AI synthesized snippets of the Content in search results);</p>
<p>(6) take action that imposes an unreasonable or disproportionately large load on our network or infrastructure;</p>
<p>(7) do anything that could disable, damage or change the functioning or appearance of the Services, including the presentation of advertising; and</p>
<p>(8) perform text and data mining activities under Art. 4 of the EU Directive on Copyright in the Digital Single Market.</p>
<p><span style="font-weight: 400;">4.2 Engaging in a prohibited use of the Services may result in civil, criminal, and/or administrative penalties, fines, or sanctions against the user and those assisting the user.</span></p>
<hr>
<p><a name="5"></a><strong><a id="f"></a>5. REPRESENTATIONS AND WARRANTIES; INDEMNIFICATION; LIMITATION OF LIABILITIES</strong></p>
<p><span style="font-weight: 400;">5.1 You represent, warrant and covenant that: (1) no materials of any kind submitted through your account will: (a) violate, plagiarize, or infringe upon the rights of any third party, including copyright, trademark, privacy or other personal or proprietary rights, or (b) contain libelous or otherwise unlawful material; (2) you are at least thirteen years old if you are in the USA and the UK, and sixteen years old anywhere else; and (3) if you are under eighteen years old, your parent or legal guardian has read these Terms of Service and agreed to them and your use of the Service. You hereby indemnify, defend and hold harmless NYT and all officers, directors, owners, agents, information providers, affiliates, licensors and licensees (collectively, the “</span><strong>Indemnified Parties</strong>”<span style="font-weight: 400;">) from and against any and all liability and costs, including, without limitation, reasonable attorneys' fees, incurred by the Indemnified Parties in connection with any claim arising out of: (1) any breach by you or any user of your account of these Terms of Service or the foregoing representations, warranties and covenants; or (2) your gross negligence or willful misconduct. You must cooperate as fully as reasonably required in the defense of any such claim. NYT reserves the right, at its own expense, to assume the exclusive defense and control of any matter subject to indemnification by you.</span></p>
<p><span style="font-weight: 400;">5.2 NYT does not represent or endorse the accuracy or reliability of any advice, opinion, statement, or other information displayed, uploaded, or distributed through the Services by any user, information provider or any other person or entity. NYT will not be liable to you or any other person as a result of a user’s interactions with other users. You acknowledge that any reliance upon any such opinion, advice, statement, memorandum, or information will be at your sole risk. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAWS, THE SERVICES AND ALL SOFTWARE ARE DISTRIBUTED ON AN “AS IS” BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. WHILE WE TRY OUR BEST TO ENSURE THAT THE SERVICES ARE ALWAYS AVAILABLE, UP-TO-DATE AND CORRECT, NYT DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. THERE MAY BE DELAYS, OMISSIONS, INTERRUPTIONS, AND INACCURACIES IN THE CONTENT OR OTHER MATERIAL MADE AVAILABLE THROUGH THE SERVICES. YOU SHOULD NOT RELY ON THE CONTENT AS A SUBSTITUTE FOR, NOR DOES IT REPLACE, PROFESSIONAL LEGAL, FINANCIAL, TAX OR MEDICAL ADVICE. IF YOU HAVE ANY CONCERNS OR QUESTIONS ABOUT YOUR HEALTH OR THE CONTENT ON THE SERVICES, YOU SHOULD ALWAYS CONSULT WITH A PHYSICIAN OR OTHER HEALTH-CARE PROFESSIONAL. PRIOR TO THE EXECUTION OF A PURCHASE OR SALE OF ANY SECURITY OR INVESTMENT, YOU ARE ADVISED TO CONSULT WITH YOUR BROKER OR OTHER FINANCIAL ADVISOR TO VERIFY PRICING AND OTHER INFORMATION. WE WILL HAVE NO LIABILITY FOR INVESTMENT DECISIONS BASED UPON, OR THE RESULTS OBTAINED FROM, THE CONTENT PROVIDED IN THE SITE, THE CONTENT, OR THE SERVICES. NOTHING CONTAINED IN THE SITE WILL BE CONSTRUED AS INVESTMENT ADVICE. WE ARE NOT A REGISTERED BROKER-DEALER OR INVESTMENT ADVISOR AND DO NOT GIVE INVESTMENT ADVICE OR RECOMMEND ONE PRODUCT OVER ANOTHER. YOU HEREBY ACKNOWLEDGE THAT THE USE OF THE SERVICES IS AT YOUR SOLE RISK. </span></p>
<p><span style="font-weight: 400;">5.3 </span><span style="font-weight: 400;">IN NO EVENT WILL NYT, ITS AFFILIATES AND THEIR RESPECTIVE SHAREHOLDERS, DIRECTORS, OFFICERS, EMPLOYEES, ADVERTISERS, SUPPLIERS, CONTENT PROVIDERS AND LICENSORS (“</span><strong>NYT PARTIES</strong>”<span style="font-weight: 400;">) BE LIABLE (JOINTLY OR SEVERALLY) TO YOU OR ANY OTHER PERSON AS A RESULT OF YOUR ACCESS OR USE OF THE SERVICES, SUBMISSIONS OR CONTENT FOR INDIRECT, CONSEQUENTIAL, SPECIAL, INCIDENTAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING, WITHOUT LIMITATION, LOST PROFITS, LOST SAVINGS, LOST REVENUES, LOST GOODWILL, OR COMPUTER FAILURE OR MALFUNCTION (COLLECTIVELY, THE “</span><strong>EXCLUDED DAMAGES</strong>”<span style="font-weight: 400;">). THESE LIMITATIONS APPLY WHETHER THE ALLEGED LIABILITY IS BASED ON NEGLIGENCE, TORT, CONTRACT, OR OTHER THEORY OF LIABILITY, EVEN IF ANY OF THE NYT PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF OR COULD HAVE FORESEEN ANY OF THE EXCLUDED DAMAGES, AND IRRESPECTIVE OF ANY FAILURE OF AN ESSENTIAL PURPOSE OF A LIMITED REMEDY. IF ANY APPLICABLE AUTHORITY HOLDS ANY PORTION OF THIS SECTION TO BE UNENFORCEABLE, THEN THE NYT PARTIES' LIABILITY WILL BE LIMITED TO THE FULLEST POSSIBLE EXTENT PERMITTED BY APPLICABLE LAW.</span></p>
<hr>
<p><a name="6"></a><strong><a id="g"></a>6. REGISTRATION AND SECURITY</strong></p>
<p><span style="font-weight: 400;">6.1 As part of the registration or account creation process, you will create login credentials by selecting a password and providing an e-mail address or by linking another account, such as your Apple, Facebook or Google accounts. You also can be requested to provide certain registration information, which must be accurate and updated.</span></p>
<p><span style="font-weight: 400;">Each registration is for a single user only. You are not allowed to share your registration login credentials or give your login credentials to anyone else. We may cancel or suspend your access to the Services if you share your login credentials. You are responsible for maintaining the confidentiality of your password, which you will not have to reveal to any representative or agent of NYT. You may not: (1) select or use the login credentials of another person with the intent to impersonate that person; (2) use login credentials in which another person has rights without such person's authorization; or (3) use login credentials that we, in our sole discretion, deem offensive. Failure to comply with these requirements will constitute a breach of these Terms of Service, which may result in immediate suspense or termination of your account. You must provide us with accurate, complete, and updated registration information about yourself.</span></p>
<p><span style="font-weight: 400;">You consent to receive notifications from us electronically to the e-mail address you provide to us. You agree that all notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. You agree that you have the ability to store such electronic communications such that they remain accessible to you in an unchanged form.</span></p>
<p><span style="font-weight: 400;">6.2 Please <a href="https://help.nytimes.com/hc/en-us/articles/115015385887#care">notify us</a></span><span style="font-weight: 400;"> of any known or suspected unauthorized use(s) of your account, or any known or suspected breach of security, including loss, theft, or unauthorized disclosure of your password or credit card information.</span></p>
<p><span style="font-weight: 400;">6.3 You must be 13 years or older to use any part of the Services in the USA and the UK, and 16 years or older anywhere else. If you are less than 18 years of age and would like to use, subscribe or register to any part of the Services, please ask your parent or legal guardian to review and agree to these Terms of Service before you use any part of the Services or ask them to complete the purchase and/or registration on your behalf.</span></p>
<p><span style="font-weight: 400;">6.4 You are responsible for all usage or activity on your account with NYT, including use of the account by any third party authorized by you to use your login credentials. Any fraudulent, abusive, or otherwise illegal activity may be grounds for termination of your account, at our sole discretion, and we may refer you to appropriate law-enforcement agencies.</span></p>
<p><span style="font-weight: 400;">6.5 </span><span style="font-weight: 400;">If your access to any Service has been provided by or through a third party (for example, your employer or an educational institution at which you are a student) (each, a “</span><strong>Client</strong><span style="font-weight: 400;">”), the Client may have provided us with information about you to enable us to provide you with access to the Services and distinguish you from other subscribers (such as your IP address, email address or name). </span></p>
<p><span style="font-weight: 400;">6.6. We cannot and do not guarantee that any of the Services will be free from viruses or other code that may have contaminating or destructive elements. It is your responsibility to implement appropriate IT security safeguards (including anti-virus and other security checks) to satisfy your particular requirements as to the safety and reliability of the Services.</span></p>
<p><span style="font-weight: 400;">6.7. If there is a dispute between participants on this site, or between users and any third party, you agree that NYT is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release NYT, its subsidiaries, its officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services. </span></p>
<hr>
<p><a name="7"></a><strong><a id="h"></a>7. FEES AND PAYMENTS</strong></p>
<p><span style="font-weight: 400;">7.1. We reserve the right at any time to charge fees for access to portions of the Services or the Services as a whole. In no event, however, will you be charged for access to the Services unless we obtain your prior agreement to pay such charges. Thus, if at any time we require a fee for portions of the Services that are now free, we will give you advance notice of such fees. You may cancel your account at any time (see <a href="#10.1" target="_self">Section 10.1</a> regarding termination of service). All new fees, if any, will be posted prominently on the Site and in other appropriate locations on the Service. You must pay all fees and charges incurred through your account at the rates in effect for the billing period in which such fees and charges are incurred, including, but not limited to charges for any digital products or services offered for sale through the Services by us or by any other vendor or service provider. All fees and charges will be billed to and paid for by you. You shall pay all applicable taxes relating to use of the Services through your account.</span></p>
<hr>
<p><a name="8"></a><strong>8. THIRD-PARTY CONTENT AND LINKS TO THIRD-PARTY WEBSITES.</strong></p>
<p><span style="font-weight: 400;">8.1 The Services contain links to third-party websites, services, resources, and advertisers (collectively, “</span><strong>Linked Content</strong><span style="font-weight: 400;">”). NYT does not control, endorse, sponsor, recommend or otherwise accept responsibility for any of this Linked Content. Because we are not responsible for the availability of these outside resources, or their contents or privacy practices, you should direct any concerns regarding any Linked Content to such site. </span>When you access Linked Content, you accept that there are risks in doing so, and that NYT is not responsible for such risks. We encourage you to be aware when you leave the Services and to read the terms and conditions and privacy policy of each third-party website or service that you visit or utilize. Because we are not responsible for the availability of these outside resources, or their contents or privacy practices, you should direct any concerns regarding any Linked Content to such site.</p>
<p>In addition, NYT will not and cannot monitor, verify, censor, or edit the content of any third-party site or service. By using the Services, you release and hold us harmless from any and all liability arising from your use of any third-party website or service.</p>
<p>Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties, or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that NYT shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings.</p>
<hr>
<p><a name="9"></a><strong>9. SOFTWARE LICENSES</strong></p>
<p><span style="font-weight: 400;">We grant you a limited, revocable, and non-transferable license to use the mobile applications (“Apps”) on devices you own or have a legal right to use in accordance with these Terms of Service, the Terms of Sale (where applicable), and any additional terms specific to the particular application. You have no rights to the proprietary software and related documentation, or any enhancements or modifications thereto, provided to you in order to access the Services (“</span><strong>Software</strong>”<span style="font-weight: 400;">). You may not sublicense, assign or transfer any licenses granted by NYT, and any attempt at such sublicense, assignment or transfer will be null and void. You may make one copy of such Software for archival purposes only. You may not otherwise copy, distribute, modify, reverse engineer, or create derivative works from Software.</span></p>
<hr>
<p><a name="10"></a><strong>10. TERMINATION; SURVIVAL</strong></p>
<p><a name="10.1"></a><span style="font-weight: 400;">10.1 You may terminate your NYT account by calling Customer Care at 866-273-3612 during limited hours (please see our <a href="https://help.nytimes.com/hc/en-us/articles/115014792927-International-contact-info" target="_blank" rel="noopener">international contact information</a> if you are outside the U.S.) or chatting with Customer Care <a href="https://help.nytimes.com/hc/en-us/articles/115015385887-Contact-us" target="_blank" rel="noopener">here</a> during limited hours. Cancellation</span><span style="font-weight: 400;"> of paid digital products will be governed by our </span><a href="https://help.nytimes.com/hc/en-us/articles/115014893968-Terms-of-sale#cancellation" target="_blank" rel="noopener">Cancellation and Refund Policy for Digital Products</a><span style="font-weight: 400;">. Please note that terminating your NYT account does not automatically terminate your account with The Athletic. To terminate your account with The Athletic, please contact us directly at <span style="color: #000000; font-family: ' Times New Roman' font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><a href="https://nytimes.com/athletic/contact-support" target="_blank" rel="noopener noreferrer">nytimes.com/athletic/contact-support</a></span>.</span></p>
<p><span style="font-weight: 400;">10.2 NYT may, in its sole discretion, terminate or suspend your access to all or part of the Services for any reason, including, without limitation, breach or assignment of these Terms of Service.</span></p>
<p><span style="font-weight: 400;">10.3 </span><span style="font-weight: 400;">The provisions of these Terms of Service will survive the termination of your account or access to all or part of the Services. </span></p>
<hr>
<p><a name="11"></a><strong>11. GOVERNING LAW; JURISDICTION</strong></p>
<p><span style="font-weight: 400;">11.1 These Terms of Service have been made and will be construed and enforced in accordance with the laws of the United States of America and the State of New York as an agreement wholly performed in the State of New York without regard to their conflict of law provisions and the United Nations Conventions on Contracts (if applicable).</span></p>
<p><span style="font-weight: 400;">11.2 Any claim or cause of action arising out of or related to use of the Services or these Terms of Services must be filed within one year after such claim or cause of action arose or be forever barred. </span></p>
<hr>
<p><span style="font-weight: 400;"><a name="12"></a><strong>12. WAIVER OF CLASS ACTIONS; ARBITRATION</strong></span></p>
<p>12.1 <strong>Binding Arbitration</strong>. You and NYT agree that, except for i) claims related to intellectual property, and ii) any claims that may be brought in small claims court where the amount in controversy is properly within the jurisdiction of such court (collectively, “Excluded Claims”), any controversy or claim arising out of or relating to the Terms of Service, the Terms of Sale, your relationship to NYT as a subscriber, or your use of any of NYT’s Services, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory (the “Covered Claims”), will be resolved by binding, individual arbitration. The parties further agree that the determination of the scope, enforceability, or applicability of this Arbitration Agreement, including, but not limited to any claim that all or any part thereof of this Arbitration Agreement is void or voidable, whether a claim is subject to arbitration, and any dispute regarding the payment of administrative or arbitrator fees (including the timing of such payments and remedies for nonpayment) will be resolved exclusively by final and binding arbitration in accordance with this Arbitration Agreement. YOUR AGREEMENT TO ARBITRATION MEANS THAT FOR ALL COVERED CLAIMS, YOU ARE GIVING UP YOUR RIGHT TO FILE A LAWSUIT IN COURT AND THE RIGHT TO A TRIAL BY JURY.  INSTEAD, YOU WILL HAVE A HEARING BEFORE A NEUTRAL ARBITRATOR.</p>
<table style="border-collapse: collapse; width: 100%;" border="1">
<tbody>
<tr>
<td style="width: 100%;">
<span style="font-weight: 400;">12.2 </span><span class="wysiwyg-underline"><strong>WAIVER OF CLASS ACTIONS</strong></span>. YOU AND NYT AGREE THAT EACH PARTY MAY BRING DISPUTES RELATING TO BOTH COVERED CLAIMS AND EXCLUDED CLAIMS AGAINST THE OTHER PARTY ONLY IN AN INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING, INCLUDING, WITHOUT LIMITATION, A FEDERAL OR STATE CLASS ACTION LAWSUIT OR A CLASS ARBITRATION. If there is a final judicial determination that applicable law precludes enforcement of this paragraph’s limitations as to a particular remedy, then that remedy (and only that remedy) must be severed from the arbitration and may be sought in court. The parties agree, however, that any adjudication of remedies not subject to arbitration shall be stayed pending the outcome of any arbitrable claims and remedies. This subsection does not prevent you or us from participating in a class-wide settlement of claims.
<p>Notwithstanding the foregoing, an arbitrator may consolidate more than one person's claims if the NYT provides consent to such consolidation in writing. If a court decides that applicable law precludes enforcement of any of this paragraph's limitations as to a particular claim for relief or request for relief (such as a request for public injunctive relief) and all appeals have been exhausted or the decision is otherwise final, then the parties agree that such a claim or request for relief shall be decided by a court only after all other claims and requests for relief are arbitrated.</p>
</td>
</tr>
</tbody>
</table>
<p>12.3 <strong>Conduct of Arbitration; Governing Rules; Informal Resolution</strong>.  Arbitrations for any disputes between us relating to the Covered Claims will be administered by the American Arbitration Association (“AAA”) in accordance with its Consumer Arbitration Rules and the Supplementary Rules for Multiple Case Filings (collectively, the “AAA Rules”). For more information about arbitration, the AAA and the arbitration process, please consult the American Arbitration Association web site at adr.org. All issues are for the arbitrator to decide, except that issues relating to the scope, application, and enforceability of the arbitration provision–including whether any claims are Covered Claims or Excluded Claims within the meaning of this provision–are for the court to decide.  As stated in <a href="#11" target="_self">Section 11</a>, New York law applies to any arbitration under this section, but the parties acknowledge that the Federal Arbitration Act governs the interpretation and enforcement of this provision.  This arbitration agreement does not preclude you from bringing issues to the attention of federal, state, or local agencies, and, if the law allows, they can seek relief against us for you.</p>
<p>Prior to initiating arbitration for a Covered Claim, both parties agree that they will provide written notice of the potential claim to the opposing party setting forth: (1) the factual and legal basis for the claim; (2) contact information for the potential claimant and their counsel, if any; and (3) the remedies sought, including the amount of claimed monetary damages (the “Notice”). Such written notice shall be provided on an individualized basis. Following receipt of the Notice by the opposing party, the parties agree to make a good faith effort for at least 60 days to resolve the claim before resorting to more formal means of resolution, including, without limitation, arbitration or any court action. To provide notice of a claim to NYT, write to <a href="mailto:legal@nytimes.com">legal@nytimes.com</a> or The New York Times Company, Attn: Legal Department, 620 Eighth Avenue, New York, NY 10018. If you are an Athletic account holder or subscriber, any demand filed by you initiating arbitration must include the email address you used to log onto The Athletic, as well as any profile associated with that account that is controlled by you.</p>
<p>The aforementioned informal dispute resolution process is a prerequisite and condition precedent to commencing any formal dispute resolution proceeding. The parties agree that any relevant limitations period and filing fees or other deadlines will be tolled while the parties engage in this informal dispute resolution process.</p>
<p>Unless you and NYT agree otherwise in writing, any hearings for the arbitration will take place (i) in a location to be determined in accordance with the AAA Rules that is reasonably convenient for you and is no more than 100 miles from your home or place of business; or (ii) at another location you and we agree upon. Payment of all filing, administration, and arbitrator fees will be governed by the AAA Rules, except that if the arbitrator finds at any time that a claim was filed frivolously, for purposes of harassment, or otherwise in bad faith, then the filing party will reimburse the other party for all costs and fees, including attorneys’ fees, associated with that claim.</p>
<p>Judgment on the award rendered by the arbitrator may be entered in any federal or state court of competent jurisdiction located in the County of New York in the State of New York. The arbitrator may award money or equitable relief in favor of only the individual party seeking relief and only to the extent necessary to provide relief warranted by that party's individual claim. To reduce the time and expense of the arbitration, the arbitrator will not provide a statement of reasons for his or her award unless requested to do so by both parties. </p>
<p>12.4 <strong>Mass Arbitrations</strong>. To increase the efficiency of administration and resolution of arbitrations, in the event 25 or more similar arbitration demands (those asserting the same or substantially similar facts or claims, and seeking the same or substantially similar relief) presented by or with the assistance or coordination of the same law firm(s) or organization(s) are submitted to AAA against NYT (a “Mass Filing”), the parties agree (i) to administer the Mass Filing in batches of 10 demands per batch (to the extent there are fewer than 10 arbitration demands left over after the batching described above, a final batch will consist of the remaining demands) with only one batch filed, processed, and adjudicated at a time; (ii) to designate one arbitrator for each demand within the batch (the same arbitrator may preside over multiple demands in a batch if the relevant claimants and NYT so agree); (iii) to accept applicable fees, including any related fee reduction determined by AAA in its discretion; (iv) that no other demands for arbitration that are part of the Mass Filing may be filed, processed, or adjudicated until the prior batch of 10 is filed, processed, and adjudicated; (v) that fees associated with a demand for arbitration included in a Mass Filing, including fees owed by NYT and the claimants, shall only be due after your demand for arbitration is included in a set of batch proceedings and that batch is properly designated for filing, processing, and adjudication; (vi) that the staged process of batched proceedings, with each set including 10 demands, shall continue until each demand (including your demand) is adjudicated or otherwise resolved; and (vii) to make good faith efforts to resolve each batch of demands within 180-days, failing which any of the claimants or NYT may cease arbitration and file in a court of competent jurisdiction.</p>
<p>Arbitrator selection for the demands in each batch shall be conducted to the greatest extent possible in accordance with the applicable AAA rules and procedures for such selection, and the arbitrator will determine the location where the proceedings for each demand within a batch will be conducted. You agree to cooperate in good faith with NYT and the arbitration provider to implement such a “batch approach” or other similar approach to provide for an efficient resolution of claims, including the payment of combined reduced fees, set by AAA in its discretion, for each batch of demands. The parties further agree to cooperate with each other and the arbitration provider or arbitrator to establish any other processes or procedures that the arbitration provider or arbitrator believe will provide for an efficient resolution of claims. Any disagreement between the parties as to whether this provision applies or as to the process or procedure for batching shall be resolved by a procedural arbitrator appointed by AAA. This “Batch Arbitration” provision shall in no way be interpreted as increasing the number of demands necessary to trigger the applicability of AAA’s Mass Arbitration Supplementary Rules or authorizing class arbitration of any kind. Unless NYT otherwise consents in writing, NYT does not agree or consent to class arbitration, private attorney general arbitration, or arbitration involving joint or consolidated claims under any circumstances, except as set forth in this section 12.4. If your demand for arbitration is included in the Mass Filing, your claims will remain tolled until your demand for arbitration is decided, withdrawn, or is settled. The parties agree that this batching provision is integral to this Section 12 insofar as it applies to a Mass Filing. If the batching provision in this Section 12.4 or the engagement of a mediator in Section 12.5 is found to be invalid, unenforceable or illegal, then the entirety of this Section 12 shall be null and void, and neither you nor NYT shall be entitled to arbitrate any claim that is a part of the Mass Filing.</p>
<p>12.5 <strong>Mediation Following First Batch in a Mass Filing</strong>. The results of the first batch of demands will be given to a AAA mediator selected from a group of 5 mediators initially proposed by AAA, with NYT and the remaining claimants’ counsel being able to strike one mediator each and then rank the remaining mediators and the highest collectively ranked mediator being selected. The selected mediator will try to facilitate a resolution of the remaining demands in the Mass Filing. After the results are provided to the mediator, NYT, the remaining claimants and their counsel, and the mediator will have 90 days (the “Mediation Period”) to agree on a resolution or substantive methodology for resolving the outstanding demands. If the parties are unable to resolve the outstanding demands during the Mediation Period and cannot agree on a methodology for resolving them through further arbitrations, either NYT or any remaining claimant may opt out of the arbitration process and have the demand(s) proceed in a court of competent jurisdiction. Notice of the opt-out will be provided in writing within 60 days of the close of the Mediation Period. If neither NYT nor the remaining claimants opt out and they cannot agree to a methodology for resolving the remaining demands through further arbitration, the arbitrations will continue with the batching process. Absent notice of an opt-out, the arbitrations will proceed in the order determined by the sequential numbers assigned to demands in the Mass Filing.</p>
<p>12.6 <strong>Opt-out</strong>. You have the right to opt out and not be bound by the Arbitration Agreement by sending written notice of your decision to opt out to legal@nytimes.com with the subject line “ARBITRATION OPT-OUT.” The notice must be sent within thirty (30) days of (a) May 10, 2024; or (b) your first use of the Services, whichever is later. Otherwise, you shall be bound to arbitrate disputes in accordance with the terms of these paragraphs. If you opt out of the Arbitration Agreement, you may exercise your right to a trial by jury or judge, as permitted by applicable law, but any prior existing agreement to arbitrate disputes under any prior Arbitration Agreement between you and NYT will not apply to claims not yet filed regardless of when those claims may have accrued. If you opt out of the Arbitration Agreement, NYT also will not be bound by it.</p>
<p>12.7 For all litigation regarding Excluded Claims and any other controversy or claim for which arbitration is denied, the sole jurisdiction and venue for such litigation will be an appropriate federal or state court located in the County of New York in the State of New York.</p>
<p>12.8 All provisions of this Section 12 will survive termination of these Terms of Service and the Terms of Sale, your relationship with us, and/or your account or profile.</p>
<hr>
<p><a name="13"></a><strong>13. MISCELLANEOUS</strong></p>
<p><span style="font-weight: 400;">13.1 These Terms of Service have been made in and will be construed and enforced in accordance with New York law. Any action to enforce these Terms of Service must be brought in the federal or state courts located in New York City.</span></p>
<p><span style="font-weight: 400;">13.2 Nothing in these Terms of Service will serve to preempt the promises made </span><span style="font-weight: 400;">in our </span><a href="https://www.nytimes.com/privacy/privacy-policy" target="_blank" rel="noopener noreferrer">Privacy Policy</a><span style="font-weight: 400;">.</span></p>
<p><span style="font-weight: 400;">13.3 Correspondence should be sent to our <a href="https://help.nytimes.com/hc/en-us/articles/115015385887#care" target="_blank" rel="noopener noreferrer">Customer Care</a> team</span><span style="font-weight: 400;">.</span></p>
<p><span style="font-weight: 400;">13.4 You agree to report any violations of the Terms of Service to NYT as soon as you become aware of them. In the event you have a claim of copyright infringement with respect to material that is contained in a Service, please notify </span><a href="mailto:copyrights@nytimes.com"><span style="font-weight: 400;">copyrights@nytimes.com</span></a><span style="font-weight: 400;">. (Please direct all general questions to <a href="https://help.nytimes.com/hc/en-us/articles/115015385887#care" target="_blank" rel="noopener noreferrer">Customer Care</a></span><span style="font-weight: 400;">.)</span></p>
<p><span style="font-weight: 400;">13.5 Our failure to enforce any provision of these Terms of Service or to respond to a breach by you or other parties will not in any way constitute a waiver of our right to enforce subsequently any terms or conditions of these Terms of Service or to act with respect to similar breaches. </span></p>
<p><span style="font-weight: 400;">13.6 </span><span style="font-weight: 400;">If a provision of these Terms of Service is held invalid or unenforceable for any reason, that provision will be deemed severable and must be construed in a manner consistent with applicable law to reflect, as nearly as possible, the intention of the parties. The validity and enforceability of any remaining provisions will not be affected and those provisions will remain in full force and effect.</span></p>
<p><span style="font-weight: 400;">13.7 If you believe that your work has been copied in a way that constitutes copyright infringement, please provide us the following information in writing to NYT's Copyright Agent (see 17 U.S.C. § 512(c)(3) for further detail). Please be advised that to be effective, the Notice must include ALL of the following:</span></p>
<ol>
<li>
<span style="font-weight: 400;"> a physical or electronic signature of the person authorized to act on behalf of the owner of an exclusive copyright that is allegedly infringed;</span><span style="font-weight: 400;"><br></span>
</li>
<li><span style="font-weight: 400;">a description of the copyrighted work that you claim has been infringed;</span></li>
<li><span style="font-weight: 400;">a description of where the material that you claim is infringing is located on the Site</span></li>
<li><span style="font-weight: 400;">your address, telephone number, and email address and all other information reasonably sufficient to permit us to contact you;</span></li>
<li><span style="font-weight: 400;">a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;</span></li>
<li><span style="font-weight: 400;">a statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright owner or authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</span></li>
</ol>
<p>If you believe that any content or materials you uploaded, posted, or submitted to the NYT Service, that were subsequently removed from the NYT Service, or to which access was disabled, improperly removed or disabled, please provide the following Counter-Notification to NYT's Copyright Agent (see 17 U.S.C. § 512(g) for further detail):</p>
<ul>
<li>your physical or electronic signature.</li>
<li>a description of the materials that have been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled.</li>
<li>a statement under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled.</li>
<li>your name, address and telephone number, and a statement that you consent to the jurisdiction of the Federal District Court for the judicial district in which the address is located, and that you will accept service of process from the person who provided notification of the alleged infringement.<br><br>
</li>
</ul>
<p><strong>Notices of claimed copyright infringement should be directed to:</strong></p>
<p><strong>By mail:</strong></p>
<p><span style="font-weight: 400;">The New York Times Company</span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">620 Eighth Avenue</span><span style="font-weight: 400;"><br></span><span style="font-weight: 400;">New York, NY 10018</span></p>
<p><span style="font-weight: 400;">Attention: Copyright Agent</span><span style="font-weight: 400;"><br></span>212-556-1234</p>
<p><strong>By email: </strong><a href="mailto:copyright@nytimes.com"><span style="font-weight: 400;">copyrights@nytimes.com</span></a></p>
<p><span style="font-weight: 400;">13.8 </span><span style="font-weight: 400;">If you are a California resident, under California Civil Code Section 1789.3, you may contact us via </span><a href="https://help.nytimes.com/hc/en-us/articles/115015385887-Contact-us#:~:text=If%20you%20are%20in%20the,800%2D698%2D4637)." target="_blank" rel="noopener noreferrer">chat</a> <span style="font-weight: 400;">or by phone at 1(800) 698-4637 in order to resolve a complaint regarding the Services or to receive further information regarding use of the Services. You may also contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in writing at 1625 N. Market Blvd., Suite S-202, Sacramento, California 95834, or by telephone at (800) 952-5210.</span></p>
<p><span style="font-weight: 400;">13.9 You hereby acknowledge and agree that you are not an employee, agent, partner, or joint venture of NYT, and you do not have any authority of any kind to bind NYT in any respect whatsoever. Except as expressly set forth in the section above regarding the Application, you and NYT agree there are no third-party beneficiaries intended under these Terms.</span></p>
<hr>
<p><span style="font-weight: 400;"><strong><a name="14"></a>14. </strong></span><strong>SPECIAL TERMS</strong></p>
<p>14.1 <strong>Beta Testing</strong>.</p>
<p>NYT may invite you to review and evaluate software, applications, downloads or other features prior to their public or commercial release (hereafter “<strong>Beta Test Services</strong>”). If you choose to participate in Beta Test Services, you agree to be bound by these Special Terms and to provide NYT with certain feedback and suggestions regarding your experiences while reviewing and evaluating the Beta Test Services (“<strong>Feedback</strong>”). NYT may ask you to enter into a confidentiality agreement for each specific Beta Test Service. If so, your participation as a tester (“<strong>Tester</strong>”) is subject to that confidentiality agreement, in addition to the following terms and conditions which apply to all Beta Test Services.</p>
<p>You further agree that the Beta Test Services and any materials in the Beta Test Services, including content (collectively, “<strong>Pre-Release Materials</strong>”), are confidential or proprietary information of NYT. You agree as a condition of participating in Beta Test Services to: (1) not copy or reproduce the Pre-Release Materials; (2) safeguard the Pre-Release Materials and prevent unauthorized access to, reproduction of, disclosure of and/or unauthorized use of, the Pre-Release Materials; and (3) if applicable, fully comply with the terms and conditions of the confidentiality agreement.</p>
<p>You agree that breach of the above obligations will cause irreparable harm to NYT, and NYT is entitled to (in addition to any other remedies available to it) injunctive or other equitable relief to prevent the breach or threatened breach of your obligations. Your obligation to keep the Pre-Release Materials confidential will continue until NYT publicly distributes or has otherwise disclosed to the public through no fault of yours, the Pre-Release Materials that you are testing.</p>
<p>Upon request, you agree to immediately delete all copies of the Pre-Release Material which NYT provided to you.</p>
<p>You are invited to use Beta Test Services for the sole purpose of evaluating the Beta Test Services and assisting NYT in identifying errors. Nothing in these Special Terms or these Terms will be construed as granting you any rights or privileges of any kind with respect to the Beta Test Services or other content. The Beta Test Services are provided on an “as is” and “as available” basis and NYT makes no warranty to you of any kind, express or implied.</p>
<p>By using the Beta Test Services, you agree that: (1) participating in Beta Test Services is at your own risk and you know that the Beta Test Services may include known or unknown bugs; (2) any status indicators or preferences saved within Beta Test Services may be erased at any time; (3) NYT has no obligation to make these Beta Test Services available with or without charge for any period of time, nor to make them available at all; (4) these Terms also apply to your use of the Beta Test Services; (5) if requested, you will keep all information about the Beta Test Services confidential as stated above; (6) any Feedback you provide will become the property of NYT without any right to compensation or other obligation from NYT; (7) NYT may (or may not) use or otherwise exploit all or part of your Feedback or any derivative of it in any manner or media now known without any further remuneration, compensation or credit to you; (8) your participation to the Beta Test Services is on a purely voluntary basis and in consideration of the opportunity to assist NYT with the Beta Test Services; and (9) nothing in these Special Terms or your participation in the Beta Test Services creates any employment relationship between you and NYT.</p>
<p>In case of conflict between these Special Terms and the rest of the Terms, these Special Terms will prevail.</p>
<p>14.2 <strong>Terms for Apple Product Users</strong>. If the Application that you download, access, and/or use is downloaded from the Apple App Store:</p>
<ol>
<li>Both you and NYT acknowledge that the Terms are concluded between you and NYT only, and not with Apple, and that Apple is not responsible for the relevant mobile applications (“App”) or the Content;</li>
<li>The App is licensed to you on a limited, non-exclusive, non-transferable, non-sublicensable basis, solely to be used in connection with the Services for your private, personal, non-commercial use, subject to all the terms and conditions of these Terms as they are applicable to the Services;</li>
<li>You will only use the App in connection with an Apple device that you own or control;</li>
<li>You acknowledge and agree that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the App;</li>
<li>In the event of any failure of the App to conform to any applicable warranty, including those implied by law, you may notify Apple of such failure; upon notification, Apple’s sole warranty obligation to you will be to refund to you the purchase price, if any, of the App;</li>
<li>You acknowledge and agree that NYT, and not Apple, is responsible for addressing any claims you or any third party may have in relation to the App;</li>
<li>You acknowledge and agree that, in the event of any third-party claim that the App or your possession and use of the App infringes that third party’s intellectual property rights, NYT, and not Apple, will be responsible for the investigation, defense, settlement, and discharge of any such infringement claim;</li>
<li>You represent and warrant that you are not located in a country subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country, and that you are not listed on any U.S. Government list of prohibited or restricted parties;</li>
<li>Both you and NYT acknowledge and agree that, in your use of the App, you will comply with any applicable third-party terms of agreement which may affect or be affected by such use; and</li>
<li>Both you and NYT acknowledge and agree that Apple and Apple’s subsidiaries are third-party beneficiaries of these Terms, and that upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as the third-party beneficiary of the Terms.</li>
</ol>
<p>14.3<strong> Terms for Google Play Users</strong>. If the Application that you download, access, and/or use is downloaded from Google Play: </p>
<ol>
<li>You are allowed unlimited reinstalls of the Application without any additional fee, provided that if the Application is removed from Google Play due to (a) an allegation of infringement, or actual infringement, of any third-party Intellectual Property Right; (b) an allegation of, or actual violation of, third-party rights; or (c) an allegation or determination that such Product does not comply with applicable law, then the Application will be removed from all portions of Google Play and you will no longer have a right or ability to reinstall the Application.</li>
<li>You may also be able to claim a refund from Google for purchases made in the Application if you qualify under the <a href="https://support.google.com/googleplay/answer/2479637?p=play_refund" target="_blank" rel="noopener noreferrer">Google Play refund policy</a>.</li>
<li>Google grants to the User a nonexclusive, worldwide, and perpetual license to perform, display, and use the Application. The “User” means you and may also include, but is not limited to, a family group and family members whose accounts are joined together for the purpose of creating a family group. Family groups on Google Play will be subject to reasonable limits designed to prevent abuse of family sharing features.</li>
</ol>
          </div>
        </section>
      </div>
    </article>

    <footer>
      <div class="article-return-to-top">
        <a href="#article-container">Return to top<span class="icon-arrow-up"></span></a>
      </div>
    </footer>
  </div>


  <div class="article-votes">
    <span class="article-votes-question">Was this article helpful?</span>
    <div class="article-votes-controls" role='radiogroup'>
      <a class="button article-vote article-vote-up" data-helper="vote" data-item="article" data-type="up" data-id="115014893428" data-upvote-count="29404" data-vote-count="47973" data-vote-sum="10835" data-vote-url="/hc/en-us/articles/115014893428/vote" data-value="null" data-label="29404 out of 47973 found this helpful" data-selected-class="null" aria-selected="false" role="radio" rel="nofollow" title="Yes" href="#"></a>
      <a class="button article-vote article-vote-down" data-helper="vote" data-item="article" data-type="down" data-id="115014893428" data-upvote-count="29404" data-vote-count="47973" data-vote-sum="10835" data-vote-url="/hc/en-us/articles/115014893428/vote" data-value="null" data-label="29404 out of 47973 found this helpful" data-selected-class="null" aria-selected="false" role="radio" rel="nofollow" title="No" href="#"></a>
    </div>
    <small class="article-votes-count">
      <span class="article-vote-label" data-helper="vote" data-item="article" data-type="label" data-id="115014893428" data-upvote-count="29404" data-vote-count="47973" data-vote-sum="10835" data-vote-url="/hc/en-us/articles/115014893428/vote" data-value="null" data-label="29404 out of 47973 found this helpful">29404 out of 47973 found this helpful</span>
    </small>
  </div>

  <section class="UH-help-card-contact">

    <div id="contact_us_first_container" class="flex-row-container">
        <h4 class="UH-help-contact-title">Can't find what you're looking for?</h4>
        <div id="Chat_

    </div>
    <div class="category_article_wrapper"></div>
  </div>

<?php include ("includes/footer.php"); ?>

</div>


<!-- #main-wrapper -->

<!-- jquery Core-->
<script src="assets/js/jquery-2.1.4.min.js"></script>

<!-- Bootstrap -->
<script src="assets/js/bootstrap.min.js"></script>

<!-- Theme Menu -->
<script src="assets/js/mobile-menu.js"></script>

<!-- Owl carousel -->
<script src="assets/js/owl.carousel.min.js"></script>

<!-- Theme Script -->
<script src="assets/js/script.js"></script>
</body>

</html>